server:
  servlet:
    context-path: /api/v1
spring:
  datasource:    url: jdbc:mariadb://localhost:3305/kyobong
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver  jpa:    hibernate:      ddl-auto: create-drop
jwt:
  secret: mysecret
springdoc:
  swagger-ui:    path: doc.html